version: "3.9"
services:

#    app-account-challenger:
#      build:
#        context: ./
#        dockerfile: Dockerfile
#      restart: always
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: admin
#        MONGO_INITDB_ROOT_PASSWORD: admin
#        DB_MONGO_HOST: mongo
#        REDIS_HOST: redis
#      ports:
#        - "8080:8080"
#      depends_on:
#        - mongo
#        - redis
#      networks:
#        - broker-kafka

    mongo:
      image: mongo:latest
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_INITDB_DATABASE=mongodb
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
      ports:
        - 27017:27017
      networks:
        - broker-kafka

    redis:
      image: "redis:alpine"
      ports:
        - 6379:6379
      networks:
        - broker-kafka

networks:
  broker-kafka:
    driver: bridge