# Application Properties
Application.Port:
  value: 8081
Application.log.level:
  value: ${APP_LOG_LEVEL}

# MongoDB Properties
MongoDB.URI:
  value: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${DB_MONGO_HOST}:27017
MongoDB.DatabaseName:
  value: dbApplicationGo

# RabbitMQ Properties
RabbitMQ.URI:
  value: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:5672/${RABBITMQ_DEFAULT_VHOST}

## Rest Integration Properties
Integration.authProvider.url:
  value: http://localhost:8080
Integration.authProvider.timeout-in-milliseconds:
  value: 1000
Integration.authProvider.client.id:
  value: ${RM_USER_KEYCLOAK_CLIENT_ID}
Integration.authProvider.client.secret:
  value: ${RM_USER_KEYCLOAK_SECRET}
Integration.authProvider.realm:
  value: ${RM_USER_KEYCLOAK_REALM}
Integration.authProvider.client.id.token.exchange:
  value: ${RM_USER_KEYCLOAK_CLIENT_ID_TOKEN_EXCHANGE}
Integration.authProvider.token.public.secret:
  value: ${KEYCLOAK_TOKEN_CLIENT_PUBLIC_SECRET}

## Rest Integration Properties
#Integration.mp-order-search.url:
#  value: ${INTEGRATION_MP_ORDER_SEARCH_URL}/mp-order-search

# Cache Properties
Redis.hosts:
  value: ${REDIS_HOST}:6379

# APM Properties
Apm.server.name:
  value: app-base-go
Apm.server.otlp.collector.grpc.host:
  value: ${CLUSTER_OTLP_ENDPOINT_ENV}
Apm.server.loki.collector.http.host:
  value: ${CLUSTER_LOKI_ENDPOINT_ENV}
Apm.server.loki.collector.http.timeout.milliseconds:
  value: 2000

# Email Client Properties
Email.gmail.credentials.email:
  value: ${GMAIL_EMAIL_CLIENT_EMAIL}
Email.gmail.credentials.password:
  value: ${GMAIL_EMAIL_CLIENT_PASSWORD}