# Application Properties
Application.Port:
  value: 8080

# MongoDB Properties
MongoDB.URI:
  value: mongodb://admin:admin@localhost:27017
MongoDB.DatabaseName:
  value: dbApplicationGo

# RabbitMQ Properties
RabbitMQ.URI:
  value: amqp://admin:admin@localhost:5672/dev01_mktplace

## Rest Integration Properties
#Integration.mp-order-search.url:
#  value: https://mkt-ingress-prd.luizalabs.com/mp-order-search

# Cache Properties
Redis.hosts:
  value: localhost:6379

# APM Properties
Apm.server.name:
  value: app-base-go
Apm.server.otlp.collector.grpc.host:
  value: http://localhost/4317
Apm.server.loki.collector.http.host:
  value: 127.0.0.1/3100
Apm.server.loki.collector.http.timeout.milliseconds:
  value: 2000

# Email Client Properties
Email.gmail.credentials.email:
  value: gabriel.estmr@gmail.com
Email.gmail.credentials.password:
  value: zvqw wzdt jqiz rgul