# Application Properties
Application.Port:
  value: 8080

# MongoDB Properties
MongoDB.URI:
  value: mongodb://admin:admin@localhost:27017
MongoDB.DatabaseName:
  value: dbApplicationGo

## Kafka Properties
#Kafka.bootstrap.servers:
#  value: localhost:9093
#Kafka.group.id:
#  value: mp-indicator
#Kafka.auto.offset.reset:
#  value: earliest

## RabbitMQ Properties
#RabbitMQ.URI:
#  value: amqp://dev_mktplace:riS9udae@localhost:5672/dev01_mktplace
#
## Rest Integration Properties
#Integration.mp-order-search.url:
#  value: https://mkt-ingress-prd.luizalabs.com/mp-order-search

# Cache Properties
Redis.hosts:
  value: localhost:6379

# APM Properties
Apm.server.otlp.collector.grpc.host:
  value: http://localhost/4317
Apm.server.name:
  value: app-base-go
